name: Bug report
title: '[Bug] [Module Name] Bug title '
description: Create a report to help us improve
labels: ['type: bug', 'waiting for reply']
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to report a bug.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/difizen/libro/issues)
        first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/difizen/libro/issues) and found
            no similar issues.
          required: true

  - type: dropdown
    id: system-information
    attributes:
      label: Operating system information
      description: Operating system you use
      options:
        - Windows
        - MacOS(x86)
        - MacOS(M1, M2...)
        - Other
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version information
      description: Python version you use
      options:
        - '>3.12'
        - '3.12'
        - '3.11'
        - '3.10'
        - '3.9'
        - '<3.9'
    validations:
      required: true

  - type: textarea
    id: code-version
    attributes:
      label: libro version
      description: >
        Which version of libro are you running?
      placeholder: >
        libro: xxxx, libro-server: xxx, libro-ai:xxx, libro-sql:xxx,libro-core:xxx
    validations:
      required: false

  - type: textarea
    attributes:
      label: What happened
      description: Describe the bug
      placeholder: >
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What you expected to happen
      description: What do you think went wrong?
      placeholder: >
        Thank you for your feedback! To better understand the issue:

        1. Please describe why you believe the behavior is incorrect.

        2. Share the relevant log segments or error messages. For UI issues, screenshots are appreciated.

        3. For textual data, kindly copy and paste rather than using screenshots to facilitate easier searches in the future.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        What should we do to reproduce the problem? If you are not able to provide a reproducible case,
        please open a [Discussion](https://github.com/difizen/libro/discussions) instead.
      placeholder: >
        Steps to reproduce the behavior:

        1. Go to '...'

        2. Click on '....'

        3. Scroll down to '....'

        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any other context about the problem here?
      placeholder: >
        Add any other context about the problem here.

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        It's completely optional, but if you're interested in contributing, we're here to help! 
        If you have insights on the solution, that's even better. Libro thrives on community support, 
        and we warmly welcome new contributors.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: 'Thanks for completing our form!'
