name: 🏷️　Label(Branch Name)
on:
  pull_request_target:
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/workflows/config/pr-label-branch-name.yml
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
