name: 🏷️　Label(Patch Size)
on: pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          IGNORED: "!.gitignore\nyarn.lock\npnpm-lock.yaml"
