name: TOC Generator
on:
  push:
    branches:
      - main
      - ximo_dev
    paths:
      - 'README.md' # 只有 README.md 发生变化时触发name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          CREATE_PR: true
          GITHUB_TOKEN: ${{ secrets.LIBRO_TOKEN }}
          PR_TITLE: 'chore(docs): update TOC of readme'
