name: TOC Generator
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - README_zh.md
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      # - uses: technote-space/toc-generator@v4
      #   with:
      #     CREATE_PR: true
      #     GITHUB_TOKEN: ${{ secrets.LIBRO_TOKEN }}
      #     PR_TITLE: 'chore(docs): update TOC of readme'

      - name: Generate TOC for README.md
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README.md
          TOC_TITLE: '## Table of Contents'
          GITHUB_TOKEN: ${{ secrets.LIBRO_TOKEN }}
          PR_TITLE: 'chore(docs): update TOC of readme'
          COMMIT_MESSAGE: 'chore(docs): update TOC of readme'

      - name: Generate TOC for README_zh.md
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README_zh.md
          TOC_TITLE: '## 目录'
          CREATE_PR: true
          GITHUB_TOKEN: ${{ secrets.LIBRO_TOKEN }}
          PR_TITLE: 'chore(docs): update TOC of readme'
          COMMIT_MESSAGE: 'chore(docs): update TOC of readme'
